---
  - name: Nginx | Check if nginx present
    command: test -x /usr/sbin/nginx
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    changed_when: False
    register: nginx_present
    tags: nginx

  - name: Apache | Check if is present
    command: test -x /usr/sbin/apache2
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    changed_when: False
    register: apache2_present
    tags: nginx

  - name: Apache | Uninstall Apache2
    become: yes
    apt: name=apache2 state=absent
    when: ansible_os_family == "Debian" and apache2_present


  - name: Generate 2048bit DHE param
    shell: nohup openssl dhparam -out dhparam.pem 2048 &
    args:
        chdir: "/etc/ssl/certs"
        creates: "/etc/ssl/certs/dhparam.pem"
    async: 120
    poll: 0
    become: yes
    tags: ['dheparam','nginx']

    - name: Install Nginx-extras
    become: yes
    apt: state=present update_cache=yes pkg="{{item}}"
    when: ansible_os_family == "Debian" and nginx_present|failed
    with_items:
     - nginx-extras
    tags: nginx

  - include: passenger.yml
    when: install_passenger
    tags: passenger

  - include: php.yml
    when: install_php
    tags: php

  - name: Nginx | Create sites available/enabled directories
    file: path={{item}} state=directory mode=0755
    with_items:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
    when: ansible_os_family == "Debian" and nginx_present|failed
    tags:
      - nginx
    become: yes

  - name: Nginx | Configure include sites-enabled
    lineinfile: dest=/etc/nginx/nginx.conf regexp=".*sites-enabled.*" line="    include /etc/nginx/sites-enabled/*;" insertbefore="}" state=present
    when: ansible_os_family == "Debian" and nginx_present|failed
    become: yes
    tags: nginx

  - name: Nginx | Disable default site
    file: path=/etc/nginx/sites-enabled/default state=absent
    when: ansible_os_family == "Debian"
    become: yes
    tags: nginx

  - name: Nginx | Copy nginx.conf template
    become: yes
    template: src="nginx.conf.j2" dest="/etc/nginx/nginx.conf" owner=root group=root mode=0644
    when: ansible_os_family == "Debian"
    notify: nginx reload
    tags:
      - nginx
      - nginxconf

# Note: Logrotation not releasing the file descriptor hence it continues to write to the rotated .1 files
# More info here: https://bugs.launchpad.net/nginx/+bug/1450770
  - name: Fix logrotation bug #1450770
    replace:
      dest: '/etc/logrotate.d/nginx'
      backup: yes
      regexp: 'invoke\-rc\.d nginx rotate \>\/dev\/null 2\>\&1 \|\| true'
      replace: 'service nginx reload >/dev/null 2>&1'
      validate: '/usr/sbin/logrotate -d %s'
    tags: logrotatefix

  - include: vhost.yml
