---
nginx_default_release: ""

nginx_user: "{% if ansible_os_family == 'RedHat' or ansible_os_family == 'Suse' %}nginx{% elif ansible_os_family == 'Debian' %}www-data{% elif ansible_os_family == 'FreeBSD' %}www{% endif %}"
nginx_group: "{{nginx_user}}"

nginx_worker_processes: "{{ansible_processor_cores | default('1')}}"
nginx_worker_connections: "1024"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "64m"

nginx_proxy_cache_path: ""

nginx_remove_default_vhost: false

nginx_vhost_filename: "{{ ansible_fqdn }}_{{playbook_name}}.conf"
nginx_vhost_path: "/etc/nginx/sites-enabled"
nginx_vhosts: []
# Example vhost below, showing all available options:
# - listen: "80 default_server" # default: "80 default_server"
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
#
#   # Properties that are only added if defined:
#   error_page: ""
#   access_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }

passenger_standalone: false
install_passenger: false
install_php: false

php5_packages:
  - php5-common
  - php5-mysql
  #  - php5-suhosin
  - php5-gd
  - php5-cgi
  - php-pear
  - php5-mcrypt
  - php5-curl
  - php5-intl
  - php5-memcache
  - php5-pgsql
  - php5-sqlite
  - php5-xdebug
  - php5-xmlrpc
  - php-apc
