---
- name: Install https for apt (Ubuntu)
  apt: name=apt-transport-https state=present

- name: Get Icinga2 Apt Key for Debian OS family
  apt_key: url={{ icinga2_key }}
           state=present
           validate_certs=no

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository: repo='{{ item.repo }}'
                  update_cache=yes
                  state=present
  with_items: '{{ icinga2_deb_repos }}'

- name: Install Icinga2 on Debian OS family
  apt: pkg={{ item.package }}
       update_cache=yes
       state=latest
       install_recommends=no
  with_items: '{{ icinga2_pkg }}'

- name: Start Icinga2
  service: name=icinga2
           state=started
           enabled=yes
  when: icinga_dont_start == false

- name: Install additional Nagios plugins
  include: nagios_additional_plugins.yml
  tags: nagios-additional-plugins

- name: Add additional plugins
  copy: src="{{ item }}" dest="{{nagios_plugin_dir}}/{{ item }}" owner=nagios group=nagios mode=0755
  with_items:
    - check_aws_rds.py
    - check_reboot_required.sh
  tags: ['rdsplugin']

- name: Install boto library
  pip: name=boto state=present
  tags: ['rdsplugin']

- name: Set boto creds
  blockinfile:
    dest: "/etc/boto.cfg"
    create: yes
    owner: "{{system_default_user}}"
    group: "{{deploy_group}}"
    mode: 0660
    content: |
        [Credentials]
        # These are read-only credentials.
        aws_access_key_id = {{ aws_ro_user }}
        aws_secret_access_key = {{ aws_ro_pwd }}
  tags: ['rdsplugin']
